new challenge about interaction failures in mobile app
variability-challenges/variability-challenges.github.io pull request #11
Opened 2024-04-24 15:11 UTC by acherm

SPLC 2024

2024-04-24 16:08 UTC, tthuem requested changes
see detailed comment

2024-04-24 16:08 UTC, tthuem commented on 2024/interaction_failures_mobileapp/.index.html.~undo-tree~
> +(undo-tree-save-format-version . 1)
please avoid adding this file

2024-04-24 23:57 UTC, eulerhm requested changes
Can you please remove the hyphens from the abstract?

2024-05-03 13:05 UTC, tthuem commented
@jabiercoding @garganti @xdevroey From the history it seems that you all have rights to apply changes to the repository. Could you merge the PR or grant us (@acherm @tthuem) write access to apply changes on our own?

2024-05-03 13:06 UTC, tthuem commented
@acherm Will you revise the commits based on the feedback or shall I help out?

2024-05-03 13:11 UTC, xdevroey commented
I do not have admin rights on the repo. I cannot grant you write access. Maybe @jabiercoding, you can add us (past chairs) all in the organization variability-challenges so we can easily pass on the next chairs (and keep track of who has been chairing the track previously)?

2024-05-03 13:36 UTC, merged

2024-05-03 13:37 UTC, garganti commented
While we are investigating who can grant access to whom, I have approved the PR

2024-05-03 13:57 UTC, jabiercoding commented
Hello all, thanks @xdevroey and @garganti , the variability-challenges was a personal account so I now changed it to an organization and gave owner rights to @acherm @tthuem .

2024-05-03 15:20 UTC, tthuem commented
Many thanks!